server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: events-input-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  lifecycle:
    timeout-per-shutdown-phase: 20s
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

app:
  messaging:
    event-outcomes-topic: ${EVENT_OUTCOMES_TOPIC:event-outcomes}

logging:
  file:
    name: /logs/events-input-service.log
  level:
    root: INFO
    com.sportygroup.assignment: INFO

