DROP TABLE IF EXISTS settlement_audit;
DROP TABLE IF EXISTS bets;

CREATE TABLE bets (
    bet_id BIGINT PRIMARY KEY,
    user_id VARCHAR(32) NOT NULL,
    event_id VARCHAR(32) NOT NULL,
    event_market_id VARCHAR(32) NOT NULL,
    event_winner_id VARCHAR(32) NOT NULL,
    bet_amount DECIMAL(10, 2) NOT NULL,
    settled BOOLEAN NOT NULL DEFAULT FALSE,
    settlement_status VARCHAR(16),
    settled_at TIMESTAMP WITH TIME ZONE,
    settlement_message_id VARCHAR(64)
);

CREATE TABLE settlement_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bet_id BIGINT NOT NULL,
    event_id VARCHAR(32) NOT NULL,
    selected_winner_id VARCHAR(32) NOT NULL,
    actual_winner_id VARCHAR(32) NOT NULL,
    settlement_outcome VARCHAR(16) NOT NULL,
    bet_amount DECIMAL(10, 2) NOT NULL,
    rocketmq_message_id VARCHAR(64) NOT NULL,
    rocketmq_send_status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_bets_event_id_settled ON bets (event_id, settled);
CREATE INDEX idx_settlement_audit_event_id ON settlement_audit (event_id);

